"use client";

import { useSound } from "@web-kits/audio/react";

import {
  click,
  collapse,
  deselect,
  error,
  expand,
  focus,
  select,
  send,
  success,
  tabSwitch,
  warning,
} from "@/.web-kits/core";

/**
 * Interface sounds, the same set as konpeeyush.me (generated by
 * @web-kits/audio into .web-kits/). They're synthesised with the Web Audio
 * API, so there are no audio files to load, and they only ever play in
 * response to something the user did.
 */
export function useUiSounds() {
  return {
    /** A field is clicked. The quietest sound in the set. */
    field: useSound(focus),
    /** Plain text ↔ HTML. */
    tab: useSound(tabSwitch),
    /** Cc / Bcc fields appear / are removed. */
    reveal: useSound(expand),
    hide: useSound(collapse),
    /** A plain button press (Attach files). */
    press: useSound(click),
    /** Files added / removed. */
    add: useSound(select),
    remove: useSound(deselect),
    /** Send pressed with a valid form. */
    send: useSound(send),
    /** Outcomes. */
    success: useSound(success),
    /** Something needs fixing before sending (client-side). */
    warning: useSound(warning),
    /** The API refused or couldn't be reached. */
    error: useSound(error),
  };
}
